### ISSUE TITLE
Data Process

### ISSUE THREAD

**Issue by Angelnian** [westny/dronalize#1]
Can the processing and processing files from the processing round dataset be migrated to the processing INTERACTION dataset

**Comment by westny** [comment]
Hey @Angelnian,
Thanks for your interest. I am not sure what you are asking. Would you like the processed files from rounD to have the same format as INTERACTION, or something else?

**Comment by westny** [comment]
Hey @Angelnian , 
I just wanted to let you know that the toolbox now supports using INTERACTION. Happy coding!
